GPU: '0' # -1 is CPU


BATCH_SIZE : 4
NUM_EPOCHS : 200

OPTIM:
  LR_INIT: 1e-4

# data
DATA_DIR : 'C:\Users\shc01\Downloads\data\cropweed_total\IJRR2017\occ\1' # your dataset address
SAVE_DIR : 'D:\save\2nd_paper\boni_2nd' # save address
NUM_CLASSES : 3
RESIZE : 512

# resume training
LOAD_WEIGHTS : ''
